[package]
name = "lesson_6"
version = "0.27.1"
authors = ["taidaesal"]
edition = "2021"

[dependencies]
vulkano = "0.27.1"
winit = "0.25.0"
vulkano-win = "0.27.1"
vulkano-shaders = "0.27.1"
nalgebra-glm = "0.15.0"