[package]
name = "lesson_1"
version = "0.32.0"
authors = ["taidaesal"]
edition = "2021"

[dependencies]
dhat = "0.3.3"
vulkano = "=0.34.0"
vulkano-shaders = "=0.34.0"
vulkano-win = "=0.34.0"
winit = "=0.28.7"
