[package]
name = "face_lesson"
version = "0.18.0"
authors = ["taidaesal"]
edition = "2018"

[dependencies]
vulkano = "0.18.0"
winit = "0.22.0"
vulkano-win = "0.18.0"
vulkano-shaders = "0.18.0"
nalgebra-glm = "0.5.0"