[package]
name = "multi_light_lesson"
version = "0.20.0"
authors = ["taidaesal"]
edition = "2018"

[dependencies]
vulkano = "0.20.0"
winit = "0.24.0"
vulkano-win = "0.20.0"
vulkano-shaders = "0.20.0"
nalgebra-glm = "0.7.0"