[package]
name = "lesson_14"
version = "0.28.0"
authors = ["taidaesal"]
edition = "2021"

[dependencies]
png = "0.17.2"
vulkano = "0.28.0"
winit = "0.26.0"
vulkano-win = "0.28.0"
vulkano-shaders = "0.28.0"
nalgebra-glm = "0.16.0"
